config/routes.rb
Rails.application.routes.draw do
#  devise_for :engineers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   
#       devise_scope :engineer do
#    get 'signup', to: 'devise/registrations#new'
# end
  


#get "home#index"
  #devise_for :engineers, controllers: { omniauth_callbacks: 'engineers/omniauth_callbacks', registrations: 'registrations'} #, sessions: 'engineers/sessions'}
#    , sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

 resources :engineers
 #resources :engineers do
#   resources :recording_sessions 
# end

#     devise_scope :engineers do
#     get 'login', to: 'devise/sessions#new'
#  end
#  devise_scope :engineers do
#     get 'logout', to: 'devise/sessions#destroy'
#  end
#  devise_scope :engineer do
#     get 'home', to: 'devise/sessions#index'
#  end

 root 'recording_sessions#index'
 
   resources :recording_sessions, :artists, :studios

    # resources :engineers do
    # resources :recording_sessions # , only: :create
    #  end
#    resources :artists do
  #  resources :recording_sessions # , only: :create
 #    end
 #   resources :studios do
 #   resources :recording_sessions # , only: :create
 #   end




end

app/models/recording_session.rb
class RecordingSession < ApplicationRecord


  belongs_to :engineer
  belongs_to :artist
  belongs_to :studio

scope :incomplete, -> { where(status: false)}


validates :engineer_id, presence: true, length: { minimum: 1 }
validates :artist_id, presence: true, length: { minimum: 1 }
validates :studio_id, presence: true, length: { minimum: 1 }


end

app/controllers/recording_sessions_controller.rb
class RecordingSessionsController < ApplicationController


  def index
    @engineers = Engineer.all
    @studios = Studio.all
    @artists = Artist.all
    if params[:artist_id]
      @recording_sessions = Artist.find(params[:artist_id]).recording_sessions
    elsif params[:engineer_id]
      @recording_sessions = Engineer.find(params[:engineer_id]).recording_sessions
    elsif params[:studio_id]
      @recording_sessions = Studio.find(params[:studio_id]).recording_sessions
    else
      @recording_sessions = RecordingSession.all
   #    redirect_to action: 'index'
 end
 end



    def show
        @recording_session = RecordingSession.find(params[:id])
    end

    def new
        @recording_session = RecordingSession.new 
    end

    def edit
      @recording_session = RecordingSession.find(params[:id])
    end

    def create
      @recording_session = RecordingSession.new(recording_session_params)

      if @recording_session.save
        redirect_to @recording_session
      else
        render 'new'
      end
    end

    def update
      @recording_session = RecordingSession.find(params[:id])

      if @recording_session.update(recording_session_params)
        redirect_to @recording_session
      else
        render 'edit'
      end
    end

    def destroy
      @recording_session = RecordingSession.find(params[:id])
      @recording_session.destroy

      redirect_to recording_sessions_path
    end


end

app/helpers/recording_sessions_helper.rb
module RecordingSessionsHelper
end

app/views/recording_sessions/_edit_partial.html.erb
<%= form_for [@engineer, @recording_session] do |p| %>

<h2>Edit Session</h2>
<h4>Use the dropdown menus below:</h4>
<!-- Errors MESSAGING -->
<%if @recording_session.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@recording_session.errors.count, "error") %>
    prohibited this item from being saved:
    <% @recording_session.errors.full_messages.each do |msg| %>
  </h2>
  <ul style="list-style: none;">
    <li>
      <div class="alert alert-danger"><%= msg %></div>
    </li>
    <% end %>
    <% end %>
  </ul>


  <!-- EDIT FORM -->
  <h5>
    <label>Studio Location:</label><br>
    <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.location, p.id] }, {prompt: 'Book Studio'}) %>
    <br>
    <br>
    <label>Session Date:</label><br>
    <%= select("recording_session", "appointment_date", @recording_sessions.collect {|p| [ p.appointment_date, p.id] }, {prompt: 'Select Date and Time'}) %>

    <br>
    <br>
    <label>Recording Engineer:</label><br>
    <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
    <br>
    <br>
    <label>Recording Artist:</label><br>
    <%= select("recording_session", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'} ) %>
    <br>
    <br>

    <input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date"
      value="2019-05-21T07:00"></p>
    Session Date : <%= p.text_field(:appointment_date, {:class => 'form-control'}) %><br />
    <%= p.submit({:class => 'btn btn-primary'}) %>
    <% end %>
    <button> <%= link_to "Delete", recording_session_path(@recording_session), 
                                     method: :delete, 
                                     data: {confirm: 'Are you sure you want to delete this session?'},
                                     :class => 'btn btn-default' %>
    </button>
    </h4>
    <!-- END OF EDIT FORM -->

app/views/recording_sessions/_index_partial.html.erb
<!-- USED in views/RecordingSessions/index -->

<!-- EDIT FORM -->
<!-- DISPLAY recording_session.ALL -->
<section class="main">

  <%= link_to 'logout', destroy_engineer_session_path, method: :delete %>


  <% if @recording_sessions.blank? %>
  <h2>There are currently no recording sessions scheduled.</h2>
  <% else %>
  <h2>Scheduled Recording Sessions</h1>
    <br>

    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Engineer</th>
          <th>Artist</th>
          <th>Studio</th>
          <th>Location</th>
          <th>Recording Session Date</th>
          <th>Complete</th>
          <th>Cancel</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% RecordingSession.incomplete.order('appointment_date ASC').each do |c| %>
      <div class="well">
        <tbody>
          <tr>
            <td><%= link_to c.id, recording_session_path(c)%></td>
            <td><%= link_to c.engineer.name.capitalize, engineer_path(c.engineer) %></a></td>
            <td><%= link_to c.artist.name, artist_path(c.artist)%></td>
            <td><%= link_to c.studio.name.capitalize, studio_path(c.studio)%></td>
            <td><%= link_to c.studio.location.capitalize, studio_path(c.studio)%></td>
            <td><%= link_to c.appointment_date.time.to_formatted_s(:rfc822), recording_session_path(c)%></td>

            <td><%= c.status %></td>
            <td>
              <%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %>
            </td>

          </tr>

          <% end %>
        </tbody>
    </table>
    <%= link_to "LINK to ALL SESSIONS via (index_partial) ", recording_sessions_path(@recording_session), :class => 'btn btn-default' %>
    </div>
    <p> <% end %> </p>

    <!-- END OF EDIT FORM -->

app/views/recording_sessions/edit.html.erb
<body>
  <%= render 'edit_partial', form: @recording_session %>
  <br>
  <!-- Last -->

app/views/recording_sessions/index.html.erb
<br>
<br>
<br>
<br>

<%= render 'index_partial', form: @recording_session %>

app/views/recording_sessions/new.html.erb
<!-- NEW FORM -->
<%= form_for [@engineer, @recording_session], url: {action: "create"} do |p| %>

<h2>Create a New Session</h2>
<h4>Use the dropdown menus below:</h4>
<br>
<%if @recording_session.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@recording_session.errors.count, "error") %>
        prohibited this item from being saved:
        <% @recording_session.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
        <li>
            <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
    </ul>
    <%  end %>

    <h5>
        <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.id] }, {prompt: 'Book Studio'}) %>
        <br>
        <br>
        <%= select("recording_session", "appointment_date", @recording_sessions.collect {|p| [ p.appointment_date] }, {prompt: 'Select Date and Time'}) %>

        <br>
        <br>
        <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
        <br>
        <br>
        <%= select("recording_session", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'}) %>

        <br>
        <br>

        <%= p.submit({:class => 'btn btn-primary'}) %>
        <% end %>
        </h4>
        <!-- END OF NEW FORM -->