config/routes.rb
Rails.application.routes.draw do
#  devise_for :engineers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   
#       devise_scope :engineer do
#    get 'signup', to: 'devise/registrations#new'
# end
  


#get "home#index"
  #devise_for :engineers, controllers: { omniauth_callbacks: 'engineers/omniauth_callbacks', registrations: 'registrations'} #, sessions: 'engineers/sessions'}
#    , sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

 resources :engineers
 #resources :engineers do
#   resources :recording_sessions 
# end

#     devise_scope :engineers do
#     get 'login', to: 'devise/sessions#new'
#  end
#  devise_scope :engineers do
#     get 'logout', to: 'devise/sessions#destroy'
#  end
#  devise_scope :engineer do
#     get 'home', to: 'devise/sessions#index'
#  end

 root 'recording_sessions#index'
 
   resources :recording_sessions, :artists, :studios

    # resources :engineers do
    # resources :recording_sessions # , only: :create
    #  end
#    resources :artists do
  #  resources :recording_sessions # , only: :create
 #    end
 #   resources :studios do
 #   resources :recording_sessions # , only: :create
 #   end




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudioTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <p class="navbar-text pull-right">
    <% if engineer_signed_in? %>
    Logged in as <strong><%= current_engineer.name %></strong>. <br>
  
    <%= link_to 'Edit profile', edit_engineer_registration_path, :class => 'navbar-link' %> | <br>
    <%= link_to 'View Recording Sessions', recording_sessions_path, :class => 'navbar-link' %> | <br>
    <%= link_to "Logout", destroy_engineer_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign up", new_engineer_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_engineer_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>

  <body>


<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>


    <%= yield %>
  </body>
</html>